INSERT INTO workflow_items (ID, CREATED_DATE, CERT_NUMBER, EXPIRY_DATE, AMOUNT, USER_ID, LAST_MODIFIED, ESCALATE, STATUS) VALUES (9998,CURRENT_TIMESTAMP()-1, 1004327531, CURRENT_DATE()+100, 10.4, 'GARBR', CURRENT_TIMESTAMP(), CURRENT_DATE()+21, 1);
INSERT INTO workflow_item_status_history (workflow_id, date_effective, user_id, status) VALUES(9998,CURRENT_TIMESTAMP()-1, 'GARBR', 0);
